


######################### theme kunka condigure ##############################################
# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: Jekyll Theme
description: Just another Jekyll theme design and code by zhanxin.info.
keywords: Jekyll Theme
url: /StrayBirds
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: index.html
  - text: 分类目录 
    url: navigations/categories.html
  - text: 文章归档
    url: navigations/archives.html
  - text: 联系我
    url: navigations/contact.html
  - text: 友情链接
    url: navigations/links.html

#Author config
author:
    name: sunlylorn
    email: sunlylorn@qq.com
    imageLink: https://avatars1.githubusercontent.com/u/2216659
    simpleIntro: 我是 锅巴巴
    detailIntro:
      <p>一直致力于自然语言处理，机器学习，数据挖掘领域的学习和实践！</p>
      <p><b><i>教育背景</i></b></p>
      <p>哈尔滨工业大学 计算机系（本科）</p>
      <p>哈尔滨工业大学 自然语言处理实验室（硕士）</p>
      <p><b><i>工作经历</i></b></p>
      <p>2008.7 ~ 2010.8 腾讯</p>
      <p>2010.8 ~ 至今 奇虎360 好搜NLP技术部</p>
      <p><b><i>专利</i></b></p>
      <p>第一发明人。“一种基于问答知识库的问答对质量评价方法”</p>
      <p>第一发明人。“一种基于用户行为的相似短文本检测算法”</p>
      <p>第一发明人。“一种基于最长公共子串的影视名挖掘算法”</p>
      <p><b><i>著作</i></b></p>
      <p>Thread Segmentation based Answer Detection in Chinese Online Forums. Acta Automatica Sinica, 2013.</p>
      <p>Modeling Semantic Relevance for Question-Answer Pairs in Web Social Communities. ACL, 2010.</p>
      <p>A Study of Features on Primary Question Detection in Chinese Online Forums. FSKD2010.</p>
      <p>A Clustering based Fast Detection Algorithm for Large Scale Duplicate Emails. ICMLC-IWWIP, 2010.</p>
      <p>Extracting Chinese Question-Answer Pairs from Online Forums. IEEE SMC, 2009

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com

#Links
customLinks:
  - item:
    - text: sunlylorn
      url: http://blog.csdn.net/sunlylorn
    message: 朋友

#comment config
disqus:
  config: true
  id: sunlylorn


#################################### global configure #######################################

username: sunlylorn
baseurl: 
markdown: redcarpet
safe: false
highlighter: pygments
title: 锅巴巴
description: 黑发不知勤学早，白首方悔读书迟
theme: kunka
disqusname: sunlylorn

# theme can be: hack, leap-day, merlot, midnight, minimal, modernist, slate, time-machine, kunka
# those themes are all come from GitHub Pages Themes
